services:
  - type: web
    name: myapp-api
    runtime: docker
    rootDir: backend
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myapp-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ENABLE_DEV_AUTH
        value: "true"
      - key: GOOGLE_CLIENT_ID
        value: "695624050703-7mh0hq8629aur857u01v0lg4iudi1i23.apps.googleusercontent.com"
      - key: GEMINI_API_KEY
        sync: false

databases:
  - name: myapp-db
    plan: free
