"""Add tasks.is_broken_down

The previous revision (dc2765040d1f) was autogenerated without this
column even though the model declares it, causing UndefinedColumn
errors wherever tasks are queried.

Revision ID: b7f2e91c4a05
Revises: dc2765040d1f
Create Date: 2026-08-22 16:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b7f2e91c4a05'
down_revision: Union[str, Sequence[str], None] = 'dc2765040d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'tasks',
        sa.Column(
            'is_broken_down',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false'),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('tasks', 'is_broken_down')
