"""Add task breakdown and daily task recommendations

Revision ID: dc2765040d1f
Revises: d4e5f6a7b8c9
Create Date: 2026-08-21 21:36:35.239102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc2765040d1f'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_task_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_date', sa.Date(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('subtask_id', sa.UUID(), nullable=True),
    sa.Column('recommended_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recommended_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_task_recommendations_recommendation_date'), 'daily_task_recommendations', ['recommendation_date'], unique=False)
    op.create_index(op.f('ix_daily_task_recommendations_subtask_id'), 'daily_task_recommendations', ['subtask_id'], unique=False)
    op.create_index(op.f('ix_daily_task_recommendations_task_id'), 'daily_task_recommendations', ['task_id'], unique=False)
    op.create_index(op.f('ix_daily_task_recommendations_user_id'), 'daily_task_recommendations', ['user_id'], unique=False)
    op.create_table('task_breakdowns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_description', sa.Text(), nullable=False),
    sa.Column('subtasks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('breakdown_reasoning', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_breakdowns_task_id'), 'task_breakdowns', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_breakdowns_user_id'), 'task_breakdowns', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_breakdowns_user_id'), table_name='task_breakdowns')
    op.drop_index(op.f('ix_task_breakdowns_task_id'), table_name='task_breakdowns')
    op.drop_table('task_breakdowns')
    op.drop_index(op.f('ix_daily_task_recommendations_user_id'), table_name='daily_task_recommendations')
    op.drop_index(op.f('ix_daily_task_recommendations_task_id'), table_name='daily_task_recommendations')
    op.drop_index(op.f('ix_daily_task_recommendations_subtask_id'), table_name='daily_task_recommendations')
    op.drop_index(op.f('ix_daily_task_recommendations_recommendation_date'), table_name='daily_task_recommendations')
    op.drop_table('daily_task_recommendations')
    # ### end Alembic commands ###
