import uuid
from datetime import datetime
from typing import Any
from typing import Literal

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field
from pydantic import field_validator

from app.models.task import TaskPriority
from app.models.task import TaskProductivity
from app.models.task import TaskStatus
from app.schemas.calendar import CalendarBlockResponse
from app.schemas.task import ChecklistItem
from app.schemas.task import RepeatOverride

EntityType = Literal["task", "block"]
OperationType = Literal["upsert", "delete"]

DEFAULT_PULL_LIMIT = 200
MAX_PULL_LIMIT = 500
MAX_PUSH_OPERATIONS = 200


# ----------------------------------------------------------------------
# Task payload
# ----------------------------------------------------------------------


class TaskSyncPayload(BaseModel):
    """The full client-owned state of a task.

    Ids are generated by the client so a create is idempotent: retrying a push
    whose response was lost addresses the same row instead of creating a second
    task.
    """

    model_config = ConfigDict(extra="forbid")

    id: uuid.UUID
    title: str = Field(min_length=1, max_length=255)
    description: str | None = None
    deadline: datetime | None = None
    start_at: datetime | None = None
    end_at: datetime | None = None
    priority: TaskPriority = TaskPriority.medium
    status: TaskStatus = TaskStatus.pending
    estimated_duration: int | None = Field(default=None, ge=1, le=525600)
    actual_duration: int | None = Field(default=None, ge=0, le=525600)
    productivity: TaskProductivity | None = None
    category: str | None = Field(default=None, max_length=100)
    notes: str | None = None
    checklist: list[ChecklistItem] | None = None
    progress_percent: int = Field(default=0, ge=0, le=100)
    repeat_weekdays: list[int] | None = None
    repeat_ends_on: datetime | None = None
    repeat_overrides: dict[str, RepeatOverride] | None = None
    before_task_ids: list[uuid.UUID] | None = None
    after_task_ids: list[uuid.UUID] | None = None
    is_archived: bool = False
    created_at: datetime | None = None
    updated_at: datetime | None = None

    @field_validator("title")
    @classmethod
    def title_not_blank(cls, value: str) -> str:
        if not value.strip():
            raise ValueError("title must not be blank")
        return value.strip()


class BlockSyncPayload(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: uuid.UUID
    task_id: uuid.UUID
    title: str = Field(min_length=1, max_length=255)
    start_at: datetime
    end_at: datetime
    calendar_event_id: str | None = Field(default=None, max_length=255)
    completed_at: datetime | None = None
    completion_note: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None


# ----------------------------------------------------------------------
# Pull
# ----------------------------------------------------------------------


class PullQuery(BaseModel):
    cursor: int = Field(default=0, ge=0)
    limit: int = Field(default=DEFAULT_PULL_LIMIT, ge=1, le=MAX_PULL_LIMIT)


class SyncChangeOut(BaseModel):
    seq: int
    entity: EntityType
    entity_id: uuid.UUID
    revision: int
    operation: OperationType
    changed_at: datetime
    # Current server state. Null only when the row no longer exists, which
    # cannot happen for a tombstoned record.
    record: TaskSyncPayload | CalendarBlockResponse | None = None


class PullResponse(BaseModel):
    changes: list[SyncChangeOut]
    # The cursor to send next time. Server-issued, so nothing committed during
    # the download can be skipped.
    cursor: int
    has_more: bool


# ----------------------------------------------------------------------
# Push
# ----------------------------------------------------------------------


class PushOperation(BaseModel):
    model_config = ConfigDict(extra="forbid")

    # Client-generated and stable across retries.
    operation_id: uuid.UUID
    entity: EntityType
    # The revision the client last saw. None means "I believe this is new".
    base_revision: int | None = Field(default=None, ge=0)
    operation: OperationType
    payload: TaskSyncPayload | CalendarBlockResponse | BlockSyncPayload | None = None


class PushRequest(BaseModel):
    operations: list[PushOperation] = Field(
        min_length=1,
        max_length=MAX_PUSH_OPERATIONS,
    )


class PushResultOut(BaseModel):
    operation_id: uuid.UUID
    entity: EntityType
    entity_id: uuid.UUID
    # "applied"  - the server accepted the change
    # "conflict" - another device changed the record after the client's base
    # "replayed" - this operation id was already applied; the original result
    #              is returned unchanged
    status: Literal["applied", "conflict", "replayed"]
    revision: int
    record: TaskSyncPayload | CalendarBlockResponse | None = None
    detail: str | None = None


class PushResponse(BaseModel):
    results: list[PushResultOut]
